---
 - hosts: appservers
   become: yes
   tasks:
   # Task 1: Installing Apache Tomcat in Production
   - name: Installing apache tomcat software
     yum: 
      name: tomcat
      state: present
   # Task 2: Starting Apache
   - name: Starting apache tomcat
     service: 
      name: tomcat
      state: started 